### PR TITLE
Move type piracy in BipedRobot package

### PR DESCRIPTION
**Pull request by blegat**
https://github.com/dionysos-dev/Dionysos.jl/pull/290#issuecomment-1715990640

### CODE REVIEW

**Review by adrienbanse — APPROVED** [review]

**Comment by adrienbanse** [comment]
Just needs to be formatted

**Comment by blegat** [comment]
The ci job doesn't say what are the formatting that needs to be done. We should take the script of JuMP that says it

**Comment by adrienbanse** [comment]
@blegat Not sure I see what you mean, `using JuliaFormatter; format(".")` will do the job, it's written in the dev docs

**Comment by blegat** [comment]
Yes but the log of the ci job should say what should be changed. I think it was because it was one excess empty line so it was hard to see

**Pull request merged**
