### PR TITLE
Add BipedRobot in ci

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by adrienbanse** [comment]
@blegat I don't really understand the error in the test as this should be solved by https://github.com/JuliaRobotics/RigidBodyDynamics.jl/commit/0c096fa3cf9e87aee79e88c81fe18b76cebf61d5

**Comment by blegat** [comment]
We should probably do all the type piracy needed in the `BipedRobot` instead of in each test/example.

**Comment by adrienbanse** [comment]
We should also open issues in RigidBodyDynamics and Quaternions for ambiguity

**Comment by blegat** [comment]
Yes, I think these could be fixed upstream with package extensions

**Pull request merged**
