### PR TITLE
NaiveAbstraction renaming

### PR DESCRIPTION
**Pull request by adrienbanse**
cc @blegat @JulienCalbert 

Good naming?

### CODE REVIEW

**Comment by blegat** [comment]
Uniform or grid might be more explicit than classical

**Comment by adrienbanse** [comment]
@blegat I went for `UniformGridAbstraction`, long but explicit
OK for you?

**Review by blegat — APPROVED** [review]
Yes, much clearer :)

**Review by JulienCalbert — APPROVED** [review]

**Comment by adrienbanse** [comment]
@JuliaRegistrator register()

**Pull request merged**
