### PR TITLE
WIP: Power Converter Benchmark

### LINKED ISSUE #87: Power converter example
Example III.B. of Embedded Mixed-Integer Quadratic Optimization Using the OSQP Solver.
Their algorithm should be equivalent to using BemporadMorari algorithm with a B&B meta-solver like Juniper parametrized by the OSQP solver.
We could compare with our Branch-and-Bound.

### PR DESCRIPTION
**Pull request by johnaoga**

### CODE REVIEW

**Comment by adrienbanse** [comment]
I merged to master for fixing the documentation following https://github.com/dionysos-dev/Dionysos.jl/pull/359

**Comment by adrienbanse** [comment]
@johnaoga Is this ready to be merged? Otherwise I convert it to a draft

**Comment by blegat** [comment]
There is the failure

> The size of type `StaticArraysCore.SMatrix` is not known.

shown in the docs build that we should fix

**Comment by johnaoga** [comment]
> @johnaoga Is this ready to be merged? Otherwise I convert it to a draft

@adrienbanse you can make it a draft, it's far from being merged, I'm still working on it.

**Comment by johnaoga** [comment]
I'm closing this as well. I will recreate it whenever needed.

**Pull request closed without merging**
