### PR TITLE
Comments on upstream.jl

### PR DESCRIPTION
**Pull request by guberger**

### CODE REVIEW

**Review by blegat — APPROVED** [review]

**Comment by blegat** [comment]
These are temporary fix until the fix is made upstream (here upstream means Polyhedra.jl)

**Comment by blegat** [comment]
The first part is done in https://github.com/JuliaPolyhedra/Polyhedra.jl/pull/238

**Comment by blegat** [comment]
The second part is in https://github.com/JuliaPolyhedra/Polyhedra.jl/pull/240

**Comment by guberger** [comment]
Great! It means that we have to remove the file `upstream.jl`? If yes I can do it in this pull request...

**Comment by guberger** [comment]
@blegat Je teste hn, c'est sans doute pas la manière la plus propre puisque il faut le Manifest.toml ... N'hésite pas si tu as des remarques ;-)

**Comment by blegat** [comment]
It's a good way to test it on a PR but we'll wait for Polyhedra to be released and the Manifest.toml to be removed from git before merging this PR. At least now we know that it will work once it's released :)

**Pull request closed without merging**
