### PR TITLE
Remove BDDs and switch Cbc to HiGHS

### PR DESCRIPTION
**Pull request by adrienbanse**
Solves https://github.com/dionysos-dev/Dionysos.jl/issues/209, thanks @blegat

### CODE REVIEW

**Comment by JulienCalbert** [comment]
looks good to me, maybe just remove Revise.jl from the packages.

**Review by blegat — APPROVED** [review]

**Review by JulienCalbert — APPROVED** [review]

**Comment by adrienbanse** [comment]
@egidioln No idea I couldn't execute them with Cbc, is there another way to find out??

**Comment by egidioln** [comment]
> @egidioln No idea I couldn't execute them with Cbc, is there another way to find out??

I guess you could compare the CI logs but the prints are a bit messy... Or maybe the benchmark that @blegat added in #192 kept track of the difference

**Comment by adrienbanse** [comment]
@egidioln Yep, seems to be faster with HiGHS by a few seconds

**HiGHS**
[ Info: Solving... depth: 2
[ Info: Solved.
 20.180960 seconds (33.92 M allocations: 1.968 GiB, 3.14% gc time, 15.05% compilation time)
[ Info: Solving... depth: 2
[ Info: Solved.
  0.000062 seconds (29 allocations: 3.125 KiB)
[ Info: Solving... depth: 9
┌ Warning: Infeasible NLP problem terminated with primal status: NEARLY_FEASIBLE_POINT
└ @ Pavito ~/.julia/packages/Pavito/bhsCM/src/optimize.jl:693
┌ Warning: Infeasible NLP problem terminated with primal status: NEARLY_FEASIBLE_POINT
└ @ Pavito ~/.julia/packages/Pavito/bhsCM/src/optimize.jl:693
[ Info: Solved.
 33.197241 seconds (9.22 M allocations: 299.939 MiB, 0.18% gc time, 2.77% compilation time)
[ Info: Solving... depth: 11
[ Info: Solved.
  4.989449 seconds (13.67 M allocations: 334.307 MiB, 2.41% gc time, 0.11% compilation time)

**Cbc**
[ Info: Solving... depth: 2
 29.352243 seconds (44.63 M allocations: 2.596 GiB, 3.70% gc time, 11.82% compilation time)
[ Info: Solved.
[ Info: Solving... depth: 2
[ Info: Solving... depth: 2
  0.000080 seconds (29 allocations: 3.125 KiB)
[ Info: Solved.
[ Info: Solving... depth: 9
[ Info: Solving... depth: 9
┌ Warning: Infeasible NLP problem terminated with primal status: NEARLY_FEASIBLE_POINT
└ @ Pavito ~/.julia/packages/Pavito/bhsCM/src/optimize.jl:693
┌ Warning: Infeasible NLP problem terminated with primal status: NEARLY_FEASIBLE_POINT
└ @ Pavito ~/.julia/packages/Pavito/bhsCM/src/optimize.jl:693
[ Info: Solved.
 45.000690 seconds (7.66 M allocations: 265.536 MiB, 0.18% gc time, 1.58% compilation time)
[ Info: Solving... depth: 11
[ Info: Solving... depth: 11
[ Info: Solved.
 16.109674 seconds (11.44 M allocations: 306.517 MiB, 0.88% gc time, 0.04% compilation time)

**Pull request merged**
